feat: Реализовать функционал работы с моделями Item и User
KirillBabichenko/java-shareit pull request #1
Opened 2023-03-27 21:31 UTC by KirillBabichenko

2023-03-28 08:22 UTC, AnastasiyaFomkina requested changes

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Data
Лучше не использовать `@Data` бездумно, так как она несет за собой много скрытых проблем. Вот хорошая статья, вот отличная статья [про применение lombok](https://medium.com/nuances-of-programming/lombock-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B5%D0%B5-%D0%B8-%D0%BF%D0%BB%D0%BE%D1%85%D0%BE%D0%B5-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-4bd9cfdc5dd5)

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@AllArgsConstructor
Лишняя, так как нигде не используется конструктор со всеми параметрами

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long idUser,
`"X-Sharer-User-Id"` - лучше вынести в отдельный класс, например, `Variables` и сделать публичной константой, так как она понадобиться еще во многих местах программы

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
Все проверки должны быть на уровне сервиса, так как они являются бизнес-логикой программы

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +                .anyMatch(user -> user.getEmail().equals(verifiedUser.getEmail()))) {
Повторяется на 56 строке. Нужно вынести условие в отдельный метод

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        if (users.values().stream().anyMatch(user -> user.getEmail().equals(verifiedUser.getEmail()))) {
```suggestion
        if (users.values().stream()
            .anyMatch(user -> user.getEmail().equals(verifiedUser.getEmail()))) {
```

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +    public static UserDto toUserDto(User user) {
Нужно использовать маппер

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@Valid @RequestBody User user) {
Мы должны получать `UserDto` в параметрах

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                           @RequestBody User user) {
Нам должен приходить dto-объект

2023-03-28 08:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-03-28 23:05 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>   * TODO Sprint add-controllers.
Поправил.

2023-03-28 23:06 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Data
Спасибо. Исправил где были лишние аннотации.

2023-03-28 23:07 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@AllArgsConstructor
Поправил.

2023-03-28 23:07 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long idUser,
Сделано.

2023-03-28 23:15 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text.isEmpty()) {
Когда добавлял проверку - действительно был вопрос где ее лучше реализовать. Решил, что поскольку она касается параметра метода - то логичнее ее сразу провести и не доходить до сервисного слоя. Хотя в целом есть понимание, что в сервисе реализуем всю бизнес логику.

2023-03-28 23:16 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User createUser(@Valid @RequestBody User user) {
Поправил.

2023-03-28 23:16 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                           @RequestBody User user) {
Поправил.

2023-03-28 23:18 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Спасибо!

2023-03-29 10:37 UTC, AnastasiyaFomkina approved these changes

2023-03-30 19:15 UTC, merged