feat: Реализовать функционал бронирования вещей и добавления коммента…
KirillBabichenko/java-shareit pull request #2
Opened 2023-04-08 01:20 UTC by KirillBabichenko

…риев

2023-04-08 09:03 UTC, AnastasiyaFomkina requested changes

2023-04-08 09:03 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-shareit
Нужно удалить все не используемые параметры

2023-04-08 09:03 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  public class ItemServiceImpl implements ItemService {
Нужно добавить транзакционность в сервисы

2023-04-08 09:03 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
> +drop table if exists USERS, ITEMS, REQUEST, BOOKINGS, COMMENTS;
Можно добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/) для ускорения поиска

2023-04-08 09:03 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    LocalDateTime created;
Не хватает модификатора доступа

2023-04-09 14:36 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
Анастасия, спасибо за интересную и полезную информацию. Прочитал еще несколько статей по этой теме. Но решил пока оставить переключатель switch-case.

2023-04-09 14:37 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private State getState(String text) {
Перенес метод как статический в State. Если я правильно понял рекомендацию.

2023-04-09 14:37 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    //Добавить вещь
Поправил

2023-04-09 14:37 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
Поправил

2023-04-09 14:42 UTC, KirillBabichenko commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-shareit
У нас в ТЗ просят базу создавать в Postfresql, а проверки в git идут в базе H2, поэтому по идее нужны параметры для двух БД. Возможно стоит их оставить, или есть какой-то способ между ними переключаться?

2023-04-09 14:42 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>  public class ItemServiceImpl implements ItemService {
Добавил

2023-04-09 14:43 UTC, KirillBabichenko commented on src/main/resources/schema.sql
> +drop table if exists USERS, ITEMS, REQUEST, BOOKINGS, COMMENTS;
Добавил

2023-04-09 14:43 UTC, KirillBabichenko commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    LocalDateTime created;
Недосмотрел. Поправил.

2023-04-10 07:07 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-shareit
По хорошему h2 уже нужно удалить, все проверки должны проходить и с postgres. Смысла оставлять обе больше нет

2023-04-10 07:10 UTC, AnastasiyaFomkina requested changes

2023-04-10 07:10 UTC, AnastasiyaFomkina commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-shareit
В любом случае, закомментированного кода быть не должно - он вызывает вопросы и делает код менее чистым

2023-04-10 07:52 UTC, AnastasiyaFomkina approved these changes

2023-04-10 20:46 UTC, merged