feat: Реализовать приложение через микросервисную архитектуру
KirillBabichenko/java-shareit pull request #4
Opened 2023-04-29 00:02 UTC by KirillBabichenko

2023-04-30 07:51 UTC, AnastasiyaFomkina requested changes

2023-04-30 07:51 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingInfoDto.java
> +public class BookingInfoDto {
Нужно использовать для возвращения пользователю или удалить

2023-04-30 07:51 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public ResponseEntity<Object> getBookings(@RequestHeader(ID_SHARER) long userId,
Нужно возвращать конкретное dto, `Object` - слишком абстрактный. Поправь, пожалуйста, для всех контроллеров

2023-04-30 07:51 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<Object> createItem(@RequestHeader(ID_SHARER) Long idUser,
Если ты делаешь клиенты для уникальные для каждой рабочей сущности проекта, нужно конкретизировать ответ, а не возвращать абстрактный `Object`. Поправь, пожалуйста, во всех клиентах

2023-04-30 07:51 UTC, AnastasiyaFomkina commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Нужно удалить закомментированный код

2023-04-30 07:51 UTC, AnastasiyaFomkina commented on gateway/src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
Нужно почистить все неиспользуемые сущности в gateway

2023-04-30 19:02 UTC, KirillBabichenko commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
Исправил

2023-04-30 19:05 UTC, KirillBabichenko commented on gateway/src/main/java/ru/practicum/shareit/item/Item.java
> +public class Item {
Поправил.

2023-04-30 19:32 UTC, KirillBabichenko commented on gateway/src/main/java/ru/practicum/shareit/booking/dto/BookingInfoDto.java
> +public class BookingInfoDto {
Исправил.

2023-05-01 17:40 UTC, AnastasiyaFomkina approved these changes

2023-05-01 17:46 UTC, merged